  version: '3.8'

  services:
    backend:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      container_name: djBackend
      depends_on:
        - db

    Myredis:
      image: redis:7.0.14-alpine3.18
      container_name: MyRedisServer

    celery:
      build: .
      command: celery -A project worker --loglevel=info
      depends_on:
        - Myredis
        - backend

    db:
      image: postgres:latest
      container_name: my_postgres_container
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  volumes:
    postgres_data:
