# Generated by Django 4.2.4 on 2024-04-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
