# Generated by Django 4.2.4 on 2023-09-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_information',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
