# Generated by Django 4.2.4 on 2023-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_company_information_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_information',
            name='facebook_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='instagram_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='linkedin_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='pintrest_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company_information',
            name='twiter_link',
            field=models.URLField(),
        ),
    ]
