# Generated by Django 4.2.4 on 2023-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_code_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='and05fa575ibon7', max_length=15),
        ),
    ]
