# Generated by Django 4.2.4 on 2023-09-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='84115pie0fi74i6', max_length=15),
        ),
    ]
