# Generated by Django 4.2.4 on 2023-09-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delevery_time',
            new_name='delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='l36a32qoa3q5i07', max_length=15),
        ),
    ]
