# Generated by Django 4.2.4 on 2023-09-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_delevery_time_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='bmjk315jo4g42mb', max_length=15),
        ),
    ]
