# Generated by Django 4.2.4 on 2023-10-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderdetail_price_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='3mkm1kcg9ijc5oa', max_length=15),
        ),
    ]
