# Generated by Django 4.2.4 on 2023-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='99252662eiig34b', max_length=15),
        ),
    ]
