# Generated by Django 4.2.4 on 2023-10-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(default=10.2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='07oj9o6i6jlcaam', max_length=15),
        ),
    ]
