# Generated by Django 4.2.4 on 2023-10-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_cartdetail_price_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='4675j0of901ba58', max_length=15),
        ),
    ]
