# Generated by Django 4.2.4 on 2023-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_alter_order_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deleviry_fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="9494l1356jj9155", max_length=15),
        ),
    ]
