# Generated by Django 4.2.4 on 2023-11-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_alter_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="code",
            field=models.CharField(default="img8o4liocfq481", max_length=15),
        ),
    ]
