# Generated by Django 4.2.4 on 2023-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='liq4fapn6d20elc', max_length=15),
        ),
    ]
