# Generated by Django 4.2.4 on 2024-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='4imp8n4nn7ao1ca', max_length=15),
        ),
    ]
