# Generated by Django 4.2.4 on 2024-02-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='iog3libjiglfbi8', max_length=15),
        ),
    ]
