# Generated by Django 4.2.4 on 2024-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_cartdetail_price_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='price',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='5g559edlp84o7m6', max_length=15),
        ),
    ]
