# Generated by Django 4.2.4 on 2024-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_cartdetail_price_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='42l9d5a0io66l7d', max_length=15),
        ),
    ]
