# Generated by Django 4.2.4 on 2024-03-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='l0k3ij26g3jjqi1', max_length=15),
        ),
    ]
