# Generated by Django 4.2.4 on 2024-03-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='999a6m2geflcqk1', max_length=15),
        ),
    ]
