# Generated by Django 4.2.4 on 2024-03-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='73m6ikkm0jn007j', max_length=15),
        ),
    ]
