# Generated by Django 4.2.4 on 2024-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_coupon_end_date_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='796d1ik0pnn2gbi', max_length=15),
        ),
    ]
