# Generated by Django 4.2.4 on 2024-03-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='969gi0po1o86cac', max_length=15),
        ),
    ]
