# Generated by Django 4.2.4 on 2024-03-31 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_cart_total_after_coupon_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='4bei06oqpoi4aqe', max_length=15),
        ),
    ]
