# Generated by Django 4.2.4 on 2024-04-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='b6idafq88cd3onl', max_length=15),
        ),
    ]
