# Generated by Django 4.2.4 on 2024-04-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='23i5lii4gi4b65b', max_length=15),
        ),
    ]
