# Generated by Django 4.2.4 on 2024-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='gp9nfbk47pem38q', max_length=15),
        ),
    ]
