# Generated by Django 4.2.4 on 2024-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='ecg2df048qkkc3f', max_length=15),
        ),
    ]
