# Generated by Django 4.2.4 on 2024-04-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='d6qfp8136f56pj1', max_length=15),
        ),
    ]
