# Generated by Django 4.2.4 on 2024-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='80q0f38kceg3k59', max_length=15),
        ),
    ]
