# Generated by Django 4.2.4 on 2024-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='emldonlo8ql8b4a', max_length=15),
        ),
    ]
